[project]
name = "blank-app-template"
version = "0.1.0"
description = "A simple Streamlit app template."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "streamlit>=1.61.1",
    "pandas",
    "numpy",
    "xgboost",
    "shap",
    "matplotlib",
    "plotly",
    "openpyxl",
    "pydeck",
]

[tool.uv]
package = false
